[package]
name = "ecc"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.4"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
sha2 = "0.10"
rand = { version = "0.8", features = ["std", "rand_chacha"] }
